imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      global:        
        name_web: 'Control de Plaga Aviar'
        company: 'TECLOY Tecnología & Servicios E.I.R.L'
        year: '2015'
        directorio_css: 'bundles/app/css/'
        directorio_css_bootstrap: 'bundles/app/bootstrap/css/'
        directorio_css_font_awesome: 'bundles/app/font-awesome/4.3.0/css/'
        directorio_css_ionicons: 'bundles/app/ionicons/2.0.0/css/'
        directorio_js:  'bundles/app/js/' 
        directorio_js_bootstrap:  'bundles/app/bootstrap/js/' 
        directorio_plugins:  'bundles/app/plugins/' 
        directorio_images: 'bundles/app/images/' 
        directorio_dist_img: 'bundles/app/dist/img/' 
        idiomas: { es: 'Español', en: 'Inglés', it: 'Italiano'}
        lenguaje: "%locale%"     

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
